[arvan_servers]
arvan_dr_yousefi ansible_host=94.101.177.69 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519_taban ansible_ssh_common_args='-o ProxyCommand="nc -X 5 -x 127.0.0.1:1080 %h %p"'

[arvan_servers:vars]
ansible_python_interpreter=/usr/bin/python3
